// Generated by CoffeeScript 1.6.3
(function() {
  var Err, Handler, handler, path, util;

  path = require('path');

  Err = require('./err1st');

  util = require('util');

  Handler = (function() {
    var mapReflect;

    mapReflect = ['code', 'msg'];

    function Handler() {
      this._map = {};
      this._code = {};
      this._i18n = {};
      this.locales = ['en'];
      this.localeDir = "" + (process.cwd()) + "/locales";
      this.name = null;
      Object.defineProperties(this, {
        map: {
          get: function() {
            return this._map;
          },
          set: function(map) {
            var i, k, v, _v;
            for (k in map) {
              v = map[k];
              if (v instanceof Array) {
                this._map[k] = {};
                for (i in mapReflect) {
                  _v = mapReflect[i];
                  this._map[k][_v] = v[i];
                }
              } else if (typeof v === 'number') {
                this._map[k] = {
                  code: v
                };
              } else {
                this._map[k] = v;
              }
              if (this._map[k].code != null) {
                this._code[Number(String(this._map[k].code).slice(3))] = k;
              }
            }
            return this._map;
          }
        }
      });
      this.map = {
        DEFAULT_ERROR: [500100, 'unknown error']
      };
    }

    Handler.prototype.validate = function(fn) {
      if (typeof fn === 'function') {
        fn.call(this, this);
      }
      this._initI18n();
      return this;
    };

    Handler.prototype._initI18n = function() {
      var e, i, lang, newI18n, _ref;
      if (!this.localeDir) {
        return false;
      }
      _ref = this.locales;
      for (i in _ref) {
        lang = _ref[i];
        try {
          if (this._i18n[lang] == null) {
            this._i18n[lang] = {};
          }
          newI18n = require(path.join(this.localeDir, lang));
          this._i18n[lang] = util._extend(this._i18n[lang], newI18n);
        } catch (_error) {
          e = _error;
        }
      }
      return this._i18n;
    };

    Handler.prototype.restore = function(code) {
      return new Err(this._code[Number(code)]);
    };

    Handler.prototype.parse = function(err, options) {
      var lang, msg, _map, _oriPhrase, _phrase;
      if (options == null) {
        options = {};
      }
      if (typeof err === 'string') {
        err = new Err(err);
      }
      if (!(err instanceof Err && this.map[err.toPhrase()])) {
        _oriPhrase = (typeof err.toPhrase === "function" ? err.toPhrase() : void 0) || 'DEFAULT_ERROR';
        err = new Err('DEFAULT_ERROR');
      }
      if (!(err instanceof Err)) {
        return err;
      }
      _phrase = err.toPhrase();
      _map = this.map[_phrase];
      err.code = _map.code;
      lang = options.lang || this.locales[0];
      if (_oriPhrase != null) {
        msg = this.i18n(lang, _oriPhrase) || _map.msg;
      } else {
        msg = _map.msg || this.i18n(lang, _phrase);
      }
      if (this.name != null) {
        err.name = this.name;
      }
      if (typeof msg === 'function') {
        err.message = msg.apply(err, err.msgData);
      } else {
        err.message = msg;
      }
      return err;
    };

    Handler.prototype.i18n = function(lang, phrase) {
      var _ref, _ref1;
      if ((lang != null) && (phrase != null)) {
        return (_ref = this._i18n) != null ? (_ref1 = _ref[lang]) != null ? _ref1[phrase] : void 0 : void 0;
      } else {
        return this._i18n;
      }
    };

    return Handler;

  })();

  handler = new Handler;

  handler.Handler = Handler;

  module.exports = handler;

}).call(this);
