// Generated by CoffeeScript 1.6.3
(function() {
  var Handler, handler;

  Handler = (function() {
    function Handler() {
      this._codes = {
        succ: 200000,
        error: 500900
      };
      this._msgs = {
        succ: 'Success',
        error: 'Error'
      };
      Object.defineProperties(this, {
        codes: {
          get: function() {
            return this._codes;
          },
          set: function(codes) {
            var k, v, _results;
            _results = [];
            for (k in codes) {
              v = codes[k];
              _results.push(this._codes[k] = v);
            }
            return _results;
          }
        },
        msgs: {
          get: function() {
            return this._msgs;
          },
          set: function(msgs) {
            var k, v, _results;
            _results = [];
            for (k in msgs) {
              v = msgs[k];
              _results.push(this._msgs[k] = v);
            }
            return _results;
          }
        }
      });
    }

    Handler.prototype.validate = function() {};

    Handler.prototype.i18n = function() {};

    return Handler;

  })();

  handler = new Handler;

  handler.Handler = Handler;

  module.exports = handler;

}).call(this);
